In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # this is used for the plot the graph 
import os
import seaborn as sns # used for plot interactive graph.
import re as regex
from sklearn.preprocessing import LabelEncoder

from matplotlib import pyplot
import itertools


In [ ]:
from google.colab import files
data_to_load = files.upload() # we will load our csv file

Saving profiles.csv to profiles.csv


We will make a data frame object to cleanup and process data to ML schems


In [ ]:
df = pd.read_csv("profiles.csv")
df['record'] = df.index
#print(len(df))
#df.head(1)

FileNotFoundError: ignored

In [ ]:
# dropping unneeded columns
df = df.drop("last_online", axis = 1)
df = df.drop(["essay0", "essay1", "essay2", "essay3", "essay4","essay5", "essay6", "essay7", "essay8", "essay9"], axis = 1)
#dropCols = df.filter(regex="err\d$").columns
#df = df.drop(dropCols,axis = 1)
df.head(5)

NameError: ignored

we need to clean sign, religion column by retrieving first word

In [ ]:
def make_newColumn(dframe, column_name):
  new_col_list = []

  sign_col = dframe[column_name]
  for s_sign in dframe[column_name]:
    first_word = ""
    all_words = []

    all_words = str(s_sign).split()
    first_word= all_words[0]
    new_col_list.append(first_word)  
  return new_col_list

df["new_sign"] = make_newColumn(df, "sign")
df["new_religion"] = make_newColumn(df, "religion")
df.head(5)
df = df.drop(["sign", "religion"], axis = 1)

Better code bellow to remove non valid rows

In [ ]:
data_columns = list(df)
num_df = (df.drop("age", axis=1).join(df["age"].apply(pd.to_numeric, errors='coerce')))
num_df = num_df[num_df["age"].notnull()]
num_df = num_df.infer_objects()



In [ ]:
new_df = num_df
new_df = new_df.drop(["location", "offspring", "job", "pets", "speaks","education", "diet"], axis = 1)

In [ ]:
new_df.dropna(subset=["ethnicity","drinks"])
new_df = new_df[new_df['ethnicity'] != 'nan']
new_df = new_df[new_df["drinks"] != 'nan']
new_df = new_df[new_df['orientation'] != 'nan']
new_df = new_df[new_df["new_sign"] != 'nan']
new_df = new_df[new_df['orientation'] != 'nan']
new_df = new_df[new_df["new_religion"] != 0]
new_df = new_df[new_df["sex"] != 0]
new_df = new_df[new_df["smokes"] != 0]
new_df = new_df[new_df["status"] != 0]
new_df = new_df[new_df["body_type"] != 'nan']
new_df = new_df[new_df["drugs"] != 'nan']
new_df

In [ ]:
print(new_df.new_religion.unique())
print(new_df.smokes.unique())
print(new_df.status.unique())

[1 3 2 4 9 5 7 6 8]
[3 1 4 5 2]
[1 4 3 2 5]


In [ ]:


cleanup_nums = {"new_sign": {"aquarius": 1, "pisces": 2, "aries": 3, "taurus": 4, "gemini": 5, "cancer": 6, "leo": 7, "virgo": 8, "libra": 9, "scorpio": 10, "sagittarius": 11,  "capricorn": 12}}

new_df = new_df.replace(cleanup_nums)
new_df.head()

body_type  drinks  drugs height  ...  record  new_sign  new_religion   age
0           7       3      1     75  ...       0         5             1  22.0
1           6       4      2     70  ...       1         6             1  35.0
7           6       3      1     65  ...       7        11             3  31.0
9           4       1      1     65  ...       9         6             2  37.0
11          6       3      1     72  ...      11         7             3  28.0

[5 rows x 13 columns]

In [ ]:
num_df = num_df.astype({'income': np.float , 'record': np.int})
num_df = num_df.astype({'sex': np.str, 'body_type': np.str, 'diet': np.str, 'drinks': np.str, 'drugs': np.str, 'education': np.str, 'ethnicity': np.str, 'location': np.str, 'job': np.str, })
num_df = num_df.astype({'offspring': np.str, 'orientation': np.str, 'pets': np.str, 'new_religion': np.str, 'new_sign': np.str, 'smokes': np.str, 'speaks': np.str, 'status': np.str })
num_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 59946 entries, 0 to 60551
Data columns (total 21 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   body_type     59946 non-null  object 
 1   diet          59946 non-null  object 
 2   drinks        59946 non-null  object 
 3   drugs         59946 non-null  object 
 4   education     59946 non-null  object 
 5   ethnicity     59946 non-null  object 
 6   height        59940 non-null  object 
 7   income        59943 non-null  float64
 8   job           59946 non-null  object 
 9   location      59946 non-null  object 
 10  offspring     59946 non-null  object 
 11  orientation   59946 non-null  object 
 12  pets          59946 non-null  object 
 13  sex           59946 non-null  object 
 14  smokes        59946 non-null  object 
 15  speaks        59946 non-null  object 
 16  status        59946 non-null  object 
 17  record        59946 non-null  int64  
 18  new_sign      59946 non-nu

In [ ]:
#print(num_df.sex.unique())
#print(num_df.status.unique())
#print(num_df.speaks.unique())
print(num_df.smokes.unique())
print(num_df.new_sign.unique())
print(num_df.new_religion.unique())

['3' '1' '0' '5' '2' '4']
['gemini' 'cancer' 'pisces' 'aquarius' 'taurus' 'virgo' 'sagittarius'
 'leo' 'nan' 'aries' 'libra' 'scorpio' 'capricorn']
['1' '0' '2' '3' '9' '4' '5' '6' '7' '8']


In [ ]:
cleanup_nums = {"sex":     {"nan": 0, "m": 1, "f": 2}, "status": {"nan": 0, "single": 1, "married": 2, "available": 3, "seeing someone": 4, "unknown": 5},
                "new_religion": {"nan": 0, "agnosticism": 1, "atheism": 2, "christianity": 3, "catholicism": 4, "buddhism": 5, "judaism":6,"hinduism": 7, "islam": 8, "other": 9  },
                "smokes": {"nan": 0, "no": 1, "yes": 2, "sometimes": 3, "trying to quit": 4, "when drinking": 5}}

num_df = num_df.replace(cleanup_nums)
num_df.head()

clean up more. remove rows with none

In [ ]:
#new_df = new_df.drop(["ethnicity"], axis = 1)
new_df

body_type  drinks  drugs height  ...  record     new_sign  new_religion   age
0              7       3      1     75  ...       0       gemini             1  22.0
1              6       4      2     70  ...       1       cancer             1  35.0
7              6       3      1     65  ...       7  sagittarius             3  31.0
9              4       1      1     65  ...       9       cancer             2  37.0
11             6       3      1     72  ...      11          leo             3  28.0
...          ...     ...    ...    ...  ...     ...          ...           ...   ...
60538          6       3      2     78  ...   60538  sagittarius             2  21.0
60542          6       3      1     61  ...   60542        virgo             2  25.0
60548          3       4      2     72  ...   60548          leo             1  24.0
60549          6       1      1     71  ...   60549  sagittarius             3  42.0
60550          4       3      3     73  ...   60550          leo             1  27.0

[23742 rows x 13 columns]

saving data on drive

In [ ]:
#print(num_df.education.unique())
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

#! mkdir "/content/gdrive/My Drive/Colab Notebooks/Cupid_Data"
#! cp profiles.csv "/content/gdrive/My Drive/Colab Notebooks/Cupid_Data"
#! ls -l "/content/gdrive/My Drive/Colab Notebooks/Cupid_Data"

new_df.to_csv('profiles_processed_data.csv', index=False)
! cp profiles_processed_data.csv "/content/gdrive/My Drive/Colab Notebooks/Cupid_Data"
! ls "/content/gdrive/My Drive/Colab Notebooks/Cupid_Data"

Mounted at /content/gdrive/
profiles.csv  profiles_preprocessed_data.csv  profiles_processed_data.csv


In [ ]:
#le = LabelEncoder()
#sex_encoded = le.fit_transform(num_df['sex'])
#status_encoded = le.fit_transform(num_df["status"])

#print(sex_encoded)
#print(status_encoded)